// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                                 = require("@glennsl/bs-jest/src/jest.js");
var BasicsInternal$ReasonmlDemoIterators = require("../src/BasicsInternal.bs.js");

Jest.test("ofList, toList", (function () {
        var partial_arg = /* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* [] */0
            ]
          ]
        ];
        var seq = function (param) {
          return BasicsInternal$ReasonmlDemoIterators.ofList(partial_arg, param);
        };
        return Jest.Expect[/* toEqual */12](/* :: */[
                    "a",
                    /* :: */[
                      "b",
                      /* :: */[
                        "c",
                        /* [] */0
                      ]
                    ]
                  ], Jest.Expect[/* expect */0](BasicsInternal$ReasonmlDemoIterators.toList(seq)));
      }));

Jest.test("length", (function () {
        var partial_arg = /* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* [] */0
            ]
          ]
        ];
        var seq = function (param) {
          return BasicsInternal$ReasonmlDemoIterators.ofList(partial_arg, param);
        };
        return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](BasicsInternal$ReasonmlDemoIterators.length(seq)));
      }));

Jest.test("map", (function () {
        var partial_arg = /* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* [] */0
            ]
          ]
        ];
        var seqIn = function (param) {
          return BasicsInternal$ReasonmlDemoIterators.ofList(partial_arg, param);
        };
        var seqOut = BasicsInternal$ReasonmlDemoIterators.map((function (x) {
                return (x << 1);
              }), seqIn);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    2,
                    /* :: */[
                      4,
                      /* :: */[
                        6,
                        /* [] */0
                      ]
                    ]
                  ], Jest.Expect[/* expect */0](BasicsInternal$ReasonmlDemoIterators.toList(seqOut)));
      }));

Jest.test("filter", (function () {
        var partial_arg = /* :: */[
          1,
          /* :: */[
            -2,
            /* :: */[
              3,
              /* :: */[
                -4,
                /* [] */0
              ]
            ]
          ]
        ];
        var seqIn = function (param) {
          return BasicsInternal$ReasonmlDemoIterators.ofList(partial_arg, param);
        };
        var seqOut = BasicsInternal$ReasonmlDemoIterators.filter((function (x) {
                return +(x >= 0);
              }), seqIn);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    1,
                    /* :: */[
                      3,
                      /* [] */0
                    ]
                  ], Jest.Expect[/* expect */0](BasicsInternal$ReasonmlDemoIterators.toList(seqOut)));
      }));

/*  Not a pure module */
