// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                                 = require("@glennsl/bs-jest/src/jest.js");
var BasicsExternal$ReasonmlDemoIterators = require("../src/BasicsExternal.bs.js");

Jest.test("ofList, toList", (function () {
        var gen = BasicsExternal$ReasonmlDemoIterators.ofList(/* :: */[
              "a",
              /* :: */[
                "b",
                /* :: */[
                  "c",
                  /* [] */0
                ]
              ]
            ]);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    "a",
                    /* :: */[
                      "b",
                      /* :: */[
                        "c",
                        /* [] */0
                      ]
                    ]
                  ], Jest.Expect[/* expect */0](BasicsExternal$ReasonmlDemoIterators.toList(gen)));
      }));

Jest.test("length", (function () {
        var gen = BasicsExternal$ReasonmlDemoIterators.ofList(/* :: */[
              "a",
              /* :: */[
                "b",
                /* :: */[
                  "c",
                  /* [] */0
                ]
              ]
            ]);
        return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](BasicsExternal$ReasonmlDemoIterators.length(gen)));
      }));

Jest.test("map", (function () {
        var genIn = BasicsExternal$ReasonmlDemoIterators.ofList(/* :: */[
              1,
              /* :: */[
                2,
                /* :: */[
                  3,
                  /* [] */0
                ]
              ]
            ]);
        var genOut = BasicsExternal$ReasonmlDemoIterators.map((function (x) {
                return (x << 1);
              }), genIn);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    2,
                    /* :: */[
                      4,
                      /* :: */[
                        6,
                        /* [] */0
                      ]
                    ]
                  ], Jest.Expect[/* expect */0](BasicsExternal$ReasonmlDemoIterators.toList(genOut)));
      }));

Jest.test("filter", (function () {
        var genIn = BasicsExternal$ReasonmlDemoIterators.ofList(/* :: */[
              1,
              /* :: */[
                -2,
                /* :: */[
                  3,
                  /* :: */[
                    -4,
                    /* [] */0
                  ]
                ]
              ]
            ]);
        var genOut = BasicsExternal$ReasonmlDemoIterators.filter((function (x) {
                return +(x >= 0);
              }), genIn);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    1,
                    /* :: */[
                      3,
                      /* [] */0
                    ]
                  ], Jest.Expect[/* expect */0](BasicsExternal$ReasonmlDemoIterators.toList(genOut)));
      }));

/*  Not a pure module */
