// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                      = require("@glennsl/bs-jest/src/jest.js");
var Gen$ReasonmlDemoIterators = require("../src/lib/gen/gen.bs.js");

function len(gen) {
  var foldFunc = function (state, _) {
    return state + 1 | 0;
  };
  return Gen$ReasonmlDemoIterators.fold(foldFunc, 0, gen);
}

Jest.test("len 0", (function () {
        var gen = Gen$ReasonmlDemoIterators.of_list(/* [] */0);
        return Jest.Expect[/* toBe */2](0, Jest.Expect[/* expect */0](len(gen)));
      }));

Jest.test("len 2", (function () {
        var gen = Gen$ReasonmlDemoIterators.of_list(/* :: */[
              "a",
              /* :: */[
                "b",
                /* [] */0
              ]
            ]);
        return Jest.Expect[/* toBe */2](2, Jest.Expect[/* expect */0](len(gen)));
      }));

exports.len = len;
/*  Not a pure module */
