// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                      = require("@glennsl/bs-jest/src/jest.js");
var Gen$ReasonmlDemoIterators = require("../src/lib/gen/gen.bs.js");

function naturalNumbers() {
  var n = [0];
  return (function () {
      var cur = n[0];
      n[0] = n[0] + 1 | 0;
      return /* Some */[cur];
    });
}

Jest.test("Gen.take", (function () {
        var take5 = Gen$ReasonmlDemoIterators.take(5, naturalNumbers(/* () */0));
        return Jest.Expect[/* toEqual */12](/* :: */[
                    0,
                    /* :: */[
                      1,
                      /* :: */[
                        2,
                        /* :: */[
                          3,
                          /* :: */[
                            4,
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ], Jest.Expect[/* expect */0](Gen$ReasonmlDemoIterators.to_list(take5)));
      }));

Jest.test("Gen.zip", (function () {
        var abc = Gen$ReasonmlDemoIterators.of_list(/* :: */[
              "a",
              /* :: */[
                "b",
                /* :: */[
                  "c",
                  /* [] */0
                ]
              ]
            ]);
        var pairs = Gen$ReasonmlDemoIterators.zip(naturalNumbers(/* () */0), abc);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    /* tuple */[
                      0,
                      "a"
                    ],
                    /* :: */[
                      /* tuple */[
                        1,
                        "b"
                      ],
                      /* :: */[
                        /* tuple */[
                          2,
                          "c"
                        ],
                        /* [] */0
                      ]
                    ]
                  ], Jest.Expect[/* expect */0](Gen$ReasonmlDemoIterators.to_list(pairs)));
      }));

exports.naturalNumbers = naturalNumbers;
/*  Not a pure module */
