// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest  = require("@glennsl/bs-jest/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");

function iter(f, theList) {
  var _l = theList;
  while(true) {
    var l = _l;
    if (l) {
      Curry._1(f, l[0]);
      _l = l[1];
      continue ;
      
    } else {
      return /* () */0;
    }
  };
}

Jest.test("iter", (function () {
        var result = [/* [] */0];
        var f = function (x) {
          result[0] = /* :: */[
            x,
            result[0]
          ];
          return /* () */0;
        };
        iter(f, /* :: */[
              "a",
              /* :: */[
                "b",
                /* :: */[
                  "c",
                  /* [] */0
                ]
              ]
            ]);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    "c",
                    /* :: */[
                      "b",
                      /* :: */[
                        "a",
                        /* [] */0
                      ]
                    ]
                  ], Jest.Expect[/* expect */0](result[0]));
      }));

exports.iter = iter;
/*  Not a pure module */
