// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                      = require("@glennsl/bs-jest/src/jest.js");
var Gen$ReasonmlDemoIterators = require("../src/lib/gen/gen.bs.js");

function joinViaIndex($staropt$star, gen) {
  var sep = $staropt$star ? $staropt$star[0] : "";
  var foldFunc = function (state, param) {
    var str = param[1];
    if (param[0]) {
      return state + (sep + str);
    } else {
      return state + str;
    }
  };
  return Gen$ReasonmlDemoIterators.fold(foldFunc, "", Gen$ReasonmlDemoIterators.zip_index(gen));
}

Jest.test("joinViaIndex", (function () {
        var gen = Gen$ReasonmlDemoIterators.of_list(/* :: */[
              "a",
              /* :: */[
                "b",
                /* :: */[
                  "c",
                  /* [] */0
                ]
              ]
            ]);
        return Jest.Expect[/* toBe */2]("a|b|c", Jest.Expect[/* expect */0](joinViaIndex(/* Some */["|"], gen)));
      }));

function joinViaLookAhead($staropt$star, gen) {
  var sep = $staropt$star ? $staropt$star[0] : "";
  var foldFunc = function (state, param) {
    var str = param[0];
    if (param[1]) {
      return state + (str + sep);
    } else {
      return state + str;
    }
  };
  return Gen$ReasonmlDemoIterators.fold(foldFunc, "", Gen$ReasonmlDemoIterators.peek(gen));
}

Jest.test("joinViaLookAhead", (function () {
        var gen = Gen$ReasonmlDemoIterators.of_list(/* :: */[
              "a",
              /* :: */[
                "b",
                /* :: */[
                  "c",
                  /* [] */0
                ]
              ]
            ]);
        return Jest.Expect[/* toBe */2]("a|b|c", Jest.Expect[/* expect */0](joinViaLookAhead(/* Some */["|"], gen)));
      }));

exports.joinViaIndex     = joinViaIndex;
exports.joinViaLookAhead = joinViaLookAhead;
/*  Not a pure module */
