// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                              = require("@glennsl/bs-jest/src/jest.js");
var Gen$ReasonmlDemoIterators         = require("../src/lib/gen/gen.bs.js");
var ParseChunks$ReasonmlDemoIterators = require("../src/ParseChunks.bs.js");

var lineArray = "\n## Intro\nThis article is\nabout something.\n## Details\nThese are the details\nabout something.\n## Conclusion\nThis article was about something.\n".trim().split((/\r?\n/g));

var chunkList = /* :: */[
  /* record */[
    /* title */"Intro",
    /* body : :: */[
      "## Intro",
      /* :: */[
        "This article is",
        /* :: */[
          "about something.",
          /* [] */0
        ]
      ]
    ]
  ],
  /* :: */[
    /* record */[
      /* title */"Details",
      /* body : :: */[
        "## Details",
        /* :: */[
          "These are the details",
          /* :: */[
            "about something.",
            /* [] */0
          ]
        ]
      ]
    ],
    /* :: */[
      /* record */[
        /* title */"Conclusion",
        /* body : :: */[
          "## Conclusion",
          /* :: */[
            "This article was about something.",
            /* [] */0
          ]
        ]
      ],
      /* [] */0
    ]
  ]
];

Jest.test("linesToChunks", (function () {
        var linesGen = Gen$ReasonmlDemoIterators.of_array(/* None */0, /* None */0, lineArray);
        var chunkGen = ParseChunks$ReasonmlDemoIterators.linesToChunks(linesGen);
        return Jest.Expect[/* toEqual */12](chunkList, Jest.Expect[/* expect */0](Gen$ReasonmlDemoIterators.to_list(chunkGen)));
      }));

Jest.test("linesToChunksImp", (function () {
        var linesGen = Gen$ReasonmlDemoIterators.of_array(/* None */0, /* None */0, lineArray);
        var chunkGen = ParseChunks$ReasonmlDemoIterators.linesToChunksImp(linesGen);
        return Jest.Expect[/* toEqual */12](chunkList, Jest.Expect[/* expect */0](Gen$ReasonmlDemoIterators.to_list(chunkGen)));
      }));

exports.lineArray = lineArray;
exports.chunkList = chunkList;
/* lineArray Not a pure module */
