// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                      = require("@glennsl/bs-jest/src/jest.js");
var Gen$ReasonmlDemoIterators = require("../src/lib/gen/gen.bs.js");

Jest.test("peek", (function () {
        var gen = Gen$ReasonmlDemoIterators.of_list(/* :: */[
              "a",
              /* :: */[
                "b",
                /* [] */0
              ]
            ]);
        var peekGen = Gen$ReasonmlDemoIterators.peek(gen);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    /* tuple */[
                      "a",
                      /* Some */["b"]
                    ],
                    /* :: */[
                      /* tuple */[
                        "b",
                        /* None */0
                      ],
                      /* [] */0
                    ]
                  ], Jest.Expect[/* expect */0](Gen$ReasonmlDemoIterators.to_list(peekGen)));
      }));

/*  Not a pure module */
