// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                      = require("@glennsl/bs-jest/src/jest.js");
var Gen$ReasonmlDemoIterators = require("../src/lib/gen/gen.bs.js");

function joinViaIndex($staropt$star, g) {
  var sep = $staropt$star ? $staropt$star[0] : "";
  return Gen$ReasonmlDemoIterators.fold((function (state, param) {
                var str = param[1];
                if (param[0]) {
                  return state + (sep + str);
                } else {
                  return state + str;
                }
              }), "", Gen$ReasonmlDemoIterators.zip_index(g));
}

Jest.test("joinViaIndex", (function () {
        return Jest.Expect[/* toBe */2]("a|b|c", Jest.Expect[/* expect */0](joinViaIndex(/* Some */["|"], Gen$ReasonmlDemoIterators.of_list(/* :: */[
                                "a",
                                /* :: */[
                                  "b",
                                  /* :: */[
                                    "c",
                                    /* [] */0
                                  ]
                                ]
                              ]))));
      }));

function joinViaLookAhead($staropt$star, g) {
  var sep = $staropt$star ? $staropt$star[0] : "";
  return Gen$ReasonmlDemoIterators.fold((function (state, param) {
                var str = param[0];
                if (param[1]) {
                  return state + (str + sep);
                } else {
                  return state + str;
                }
              }), "", Gen$ReasonmlDemoIterators.peek(g));
}

Jest.test("joinViaLookAhead", (function () {
        return Jest.Expect[/* toBe */2]("a|b|c", Jest.Expect[/* expect */0](joinViaLookAhead(/* Some */["|"], Gen$ReasonmlDemoIterators.of_list(/* :: */[
                                "a",
                                /* :: */[
                                  "b",
                                  /* :: */[
                                    "c",
                                    /* [] */0
                                  ]
                                ]
                              ]))));
      }));

exports.joinViaIndex     = joinViaIndex;
exports.joinViaLookAhead = joinViaLookAhead;
/*  Not a pure module */
