// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                                = require("@glennsl/bs-jest/src/jest.js");
var Curry                               = require("bs-platform/lib/js/curry.js");
var Gen$ReasonmlDemoIterators           = require("../src/lib/gen/gen.bs.js");
var TreeIteration$ReasonmlDemoIterators = require("../src/TreeIteration.bs.js");

var myStrTree = /* Node */[
  "a",
  /* Node */[
    "b",
    /* Empty */0,
    /* Empty */0
  ],
  /* Node */[
    "c",
    /* Node */[
      "d",
      /* Empty */0,
      /* Empty */0
    ],
    /* Empty */0
  ]
];

Jest.test("ofTree", (function () {
        var treeGen = TreeIteration$ReasonmlDemoIterators.ofTree(myStrTree);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    "a",
                    /* :: */[
                      "b",
                      /* :: */[
                        "c",
                        /* :: */[
                          "d",
                          /* [] */0
                        ]
                      ]
                    ]
                  ], Jest.Expect[/* expect */0](Gen$ReasonmlDemoIterators.to_list(treeGen)));
      }));

Jest.test("ofTree, beyond last leaf", (function () {
        var gen = TreeIteration$ReasonmlDemoIterators.ofTree(/* Node */[
              "X",
              /* Empty */0,
              /* Empty */0
            ]);
        return Jest.Expect[/* toEqual */12](/* tuple */[
                    /* Some */["X"],
                    /* None */0,
                    /* None */0
                  ], Jest.Expect[/* expect */0](/* tuple */[
                        Curry._1(gen, /* () */0),
                        Curry._1(gen, /* () */0),
                        Curry._1(gen, /* () */0)
                      ]));
      }));

exports.myStrTree = myStrTree;
/*  Not a pure module */
