// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                      = require("@glennsl/bs-jest/src/jest.js");
var Gen$ReasonmlDemoIterators = require("../src/lib/gen/gen.bs.js");

Jest.test("Gen.zip_index", (function () {
        var gen = Gen$ReasonmlDemoIterators.of_list(/* :: */[
              "a",
              /* :: */[
                "b",
                /* :: */[
                  "c",
                  /* [] */0
                ]
              ]
            ]);
        var zippedGen = Gen$ReasonmlDemoIterators.zip_index(gen);
        return Jest.Expect[/* toEqual */12](/* :: */[
                    /* tuple */[
                      0,
                      "a"
                    ],
                    /* :: */[
                      /* tuple */[
                        1,
                        "b"
                      ],
                      /* :: */[
                        /* tuple */[
                          2,
                          "c"
                        ],
                        /* [] */0
                      ]
                    ]
                  ], Jest.Expect[/* expect */0](Gen$ReasonmlDemoIterators.to_list(zippedGen)));
      }));

/*  Not a pure module */
